export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST' ;

export const USER_PROFILE_SUCCESS ='USER_PROFILE_SUCCESS'

export const USER_PROFILE_ERROR ='USER_PROFILE_ERROR';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST' ;

export const USER_UPDATE_PROFILE_SUCCESS ='USER_UPDATE_PROFILE_SUCCESS'

export const USER_UPDATE_PROFILE_ERROR ='USER_UPDATE_PROFILE_ERROR';