export const   ADMIN_GET_USER_SUCCESS ='ADMIN_GET_USER_SUCCESS';

export const   ADMIN_GET_USER_REQUEST ='ADMIN_GET_USER_REQUEST';

export const   ADMIN_GET_USER_ERROR ='ADMIN_GET_USER_ERROR';



export const   ADMIN_UPDATE_USER_SUCCESS ='ADMIN_UPDATE_USER_SUCCESS';

export const   ADMIN_UPDATE_USER_REQUEST ='ADMIN_UPDATE_USER_REQUEST';

export const   ADMIN_UPDATE_USER_ERROR ='ADMIN_UPDATE_USER_ERROR';