export const ORDER_PAY_SUCCESS ='ORDER_PAY_SUCCESS';

export const ORDER_PAY_REQUEST ='ORDER_PAY_REQUEST';

export const ORDER_PAY_ERROR ='ORDER_PAY_ERROR';

export const ORDER_PAY_RESET ='ORDER_PAY_RESET';