export const   ADMIN_GET_ORDERS_SUCCESS ='ADMIN_GET_ORDERS_SUCCESS';

export const   ADMIN_GET_ORDERS_REQUEST ='ADMIN_GET_ORDERS_REQUEST';

export const   ADMIN_GET_ORDERS_ERROR ='ADMIN_GET_ORDERS_ERROR';