export const USER_LIST_REQUEST ='USER_LIST_REQUEST';

export const USER_LIST_SUCCESS ='USER_LIST_SUCCESS';

export const USER_LIST_ERROR ='USER_LIST_ERROR';

export const ADMIN_DELETE_USER ='ADMIN_DELETE_USER';