export const USER_LIST_REQUEST ='USER_LIST_REQUEST';

export const USER_LIST_SUCCESS ='USER_LIST_SUCCESS';

export const USER_LIST_ERROR ='USER_LIST_ERROR';


export const USER_DELETE_REQUEST ='USER_DELETE_REQUEST'

export const USER_DELETE_SUCCESS ='USER_DELETE_SUCCESS'

export const USER_DELETE_ERROR ='USER_DELETE_ERROR'